Repository probabilistic-numerics/probnum, pull requests merged in 2020-12, with the labels that each got.

#261 Minor documentation configuration updates
  docs/source/conf.py
  src/probnum/random_variables/_random_variable.py
Labels: documentation

#249 Refactor preconditioning
  STYLEGUIDE.md
  docs/source/public_api/filtsmooth.rst
  docs/source/tutorials/odesolvers_from_scratch.ipynb
  docs/source/tutorials/ordinary_differential_equations.rst
  src/probnum/diffeq/__init__.py
  src/probnum/diffeq/odefiltsmooth/__init__.py
  src/probnum/diffeq/odefiltsmooth/ivp2filter.py
  src/probnum/diffeq/odefiltsmooth/ivpfiltsmooth.py
  src/probnum/diffeq/odefiltsmooth/odefiltsmooth.py
  src/probnum/diffeq/odefiltsmooth/prior.py
  src/probnum/diffeq/odesolution.py
  src/probnum/diffeq/odesolver.py
  src/probnum/filtsmooth/__init__.py
  src/probnum/filtsmooth/bayesfiltsmooth.py
  src/probnum/filtsmooth/gaussfiltsmooth/extendedkalman.py
  src/probnum/filtsmooth/gaussfiltsmooth/iterated_kalman.py
  src/probnum/filtsmooth/gaussfiltsmooth/kalman.py
  src/probnum/filtsmooth/gaussfiltsmooth/kalmanposterior.py
  src/probnum/filtsmooth/gaussfiltsmooth/unscentedkalman.py
  src/probnum/filtsmooth/statespace/__init__.py
  src/probnum/filtsmooth/statespace/discrete_transition.py
  src/probnum/filtsmooth/statespace/integrator.py
  src/probnum/filtsmooth/statespace/preconditioner.py
  src/probnum/filtsmooth/statespace/sde.py
  src/probnum/filtsmooth/statespace/transition.py
  tests/test_diffeq/test_odefiltsmooth/test_ivp2filter.py
  tests/test_diffeq/test_odefiltsmooth/test_prior.py
  tests/test_diffeq/test_odesolution.py
  tests/test_filtsmooth/test_gaussfiltsmooth/filtsmooth_testcases.py
  tests/test_filtsmooth/test_gaussfiltsmooth/test_kalmanposterior.py
  tests/test_filtsmooth/test_statespace/test_discrete_transition.py
  tests/test_filtsmooth/test_statespace/test_integrator.py
  tests/test_filtsmooth/test_statespace/test_preconditioner.py
  tests/test_filtsmooth/test_statespace/test_sde.py
Labels: diffeq, filtsmooth, improvement

#275 CI migration to Github Actions and Dependency Management
  .github/workflows/CI-build.yml
  .readthedocs.yml
  .travis.yml
  CONTRIBUTING.md
  README.md
  docs/requirements-docs.txt
  docs/source/index.rst
  requirements.txt
  setup.cfg
  src/probnum/linalg/linearsolvers/matrixbased.py
  src/probnum/random_variables/_random_variable.py
  src/probnum/utils/randomutils.py
  tests/test_filtsmooth/test_gaussfiltsmooth/filtsmooth_testcases.py
  tests/test_filtsmooth/test_gaussfiltsmooth/test_kalman.py
  tox.ini
Labels: improvement, testing and CI

#276 Problem Zoo
  docs/source/index.rst
  docs/source/public_api/filtsmooth.rst
  docs/source/public_api/problems.rst
  src/probnum/__init__.py
  src/probnum/filtsmooth/statespace/__init__.py
  src/probnum/problems/__init__.py
  src/probnum/problems/_problems.py
  src/probnum/problems/zoo/__init__.py
  src/probnum/problems/zoo/diffeq/__init__.py
  src/probnum/problems/zoo/linalg/__init__.py
  src/probnum/problems/zoo/linalg/_random_spd_matrix.py
  tests/test_problems/__init__.py
  tests/test_problems/test_zoo/__init__.py
  tests/test_problems/test_zoo/test_linalg/__init__.py
  tests/test_problems/test_zoo/test_linalg/test_random_spd_matrix.py
  tests/test_random_variables/test_normal.py
  tox.ini
Labels: improvement

#264 Automatic version bump on release
  .github/workflows/python-publish.yml
  setup.cfg
  src/probnum/problem_zoo/__init__.py
  src/probnum/problem_zoo/linalg/__init__.py
  src/probnum/problem_zoo/linalg/_random_spd_matrix.py
  src/probnum/problem_zoo/ode/__init__.py
  tests/test_problem_zoo/__init__.py
  tests/test_problem_zoo/test_linalg/__init__.py
  tests/test_problem_zoo/test_linalg/test_random_spd_matrix.py
Labels: testing and CI

#284 Remove star imports from diffeq and filtsmooth (and filtsmooth.statespace)
  src/probnum/diffeq/__init__.py
  src/probnum/diffeq/ode/__init__.py
  src/probnum/diffeq/odefiltsmooth/__init__.py
  src/probnum/filtsmooth/__init__.py
  src/probnum/filtsmooth/gaussfiltsmooth/__init__.py
  src/probnum/filtsmooth/statespace/__init__.py
  src/probnum/filtsmooth/statespace/sde.py
  tests/test_diffeq/test_odefiltsmooth/test_ivp2filter.py
Labels: diffeq, filtsmooth

#291 Simplified Binder configuration
  environment.yml
  postBuild
Labels: documentation
