Repository probabilistic-numerics/probnum, pull requests merged in 2020-08, with the labels that each got.

#79 Benchmarks using airspeed velocity
  .gitignore
  README.md
  benchmarks/__init__.py
  benchmarks/asv.conf.json
  benchmarks/distribution.py
  benchmarks/linearsolvers.py
  docs/source/development/benchmarking.rst
  docs/source/development/contributing.rst
  docs/source/index.rst
  setup.cfg
Labels: documentation, improvement

#137 Dry run benchmarks using tox to discover potential bugs
  tox.ini
Labels: improvement, testing and CI

#134 (Advanced) Indexing, Slicing, Masking, Reshaping and Transposition for Random Variables and Distributions
  src/probnum/prob/distributions/dirac.py
  src/probnum/prob/distributions/distribution.py
  src/probnum/prob/distributions/normal.py
  src/probnum/prob/randomvariable.py
  src/probnum/utils/scalarutils.py
  tests/test_prob/test_distributions/test_normal.py
  tests/test_prob/test_randomvariable.py
Labels: improvement, prob, refactoring

#148 updated coverage settings for pytest
  tox.ini
Labels: bug, testing and CI

#149 Remove all references to the development branch
  CONTRIBUTING.md
  README.md
  docs/source/development/developer_guides.rst
  docs/source/development/documentation.rst
  docs/source/development/example_notebook.rst
  docs/source/development/probnum_method.rst
  docs/source/introduction/probabilistic_numerics.rst
  docs/source/introduction/quickstart.ipynb
Labels: improvement

#172 Make tox -e pylint run all commands, even when failing
  tox.ini
Labels: testing and CI

#192 Adjusted tox config such that asv fails on benchmark error
  tox.ini
Labels: testing and CI
