Repository probabilistic-numerics/probnum, pull requests merged in 2020-10, with the labels that each got.

#218 Refactor state space
  src/probnum/diffeq/ode/ivp.py
  src/probnum/diffeq/ode/ode.py
  src/probnum/diffeq/odefiltsmooth/ivpfiltsmooth.py
  src/probnum/diffeq/odefiltsmooth/odefiltsmooth.py
  src/probnum/diffeq/odefiltsmooth/prior.py
  src/probnum/filtsmooth/__init__.py
  src/probnum/filtsmooth/gaussfiltsmooth/extendedkalman.py
  src/probnum/filtsmooth/gaussfiltsmooth/gaussfiltsmooth.py
  src/probnum/filtsmooth/gaussfiltsmooth/kalman.py
  src/probnum/filtsmooth/gaussfiltsmooth/unscentedkalman.py
  src/probnum/filtsmooth/gaussfiltsmooth/unscentedtransform.py
  src/probnum/filtsmooth/statespace/__init__.py
  src/probnum/filtsmooth/statespace/continuous/continuousmodel.py
  src/probnum/filtsmooth/statespace/continuous/linearsdemodel.py
  src/probnum/filtsmooth/statespace/discrete/discretegaussianmodel.py
  src/probnum/filtsmooth/statespace/discrete/discretemodel.py
  src/probnum/filtsmooth/statespace/statespace.py
  src/probnum/filtsmooth/statespace/transition.py
  tests/test_diffeq/test_ode/test_ivp.py
  tests/test_diffeq/test_odefiltsmooth/test_ivp2filter.py
  tests/test_diffeq/test_odefiltsmooth/test_odefiltsmooth.py
  tests/test_diffeq/test_odefiltsmooth/test_prior.py
  tests/test_diffeq/test_odesolution.py
  tests/test_filtsmooth/test_gaussfiltsmooth/test_extendedkalman.py
  tests/test_filtsmooth/test_gaussfiltsmooth/test_kalman.py
  tests/test_filtsmooth/test_gaussfiltsmooth/test_kalmanposterior.py
  tests/test_filtsmooth/test_gaussfiltsmooth/test_unscentedkalman.py
  tests/test_filtsmooth/test_statespace/test_continuous/test_continuousmodel.py
  tests/test_filtsmooth/test_statespace/test_continuous/test_linearsdemodel.py
  tests/test_filtsmooth/test_statespace/test_discrete/test_discretegaussianmodel.py
  tests/test_filtsmooth/test_statespace/test_discrete/test_discretemodel.py
Labels: refactoring

#222 Pre commit additions
  .pre-commit-config.yaml
  CONTRIBUTING.md
  tox.ini
Labels: improvement

#228 Calibration mode was not always used in the probabilistic linear solver
  src/probnum/linalg/linearsolvers/matrixbased.py
  tests/test_linalg/test_linearsolvers/test_linearsolvers.py
Labels: bug, linalg
