Repository probabilistic-numerics/probnum, pull requests merged in 2021-09, with the labels that each got.

#511 Quickstart for linear solvers
  docs/source/tutorials.rst
  docs/source/tutorials/linalg/linear_solvers_quickstart.ipynb
  docs/source/tutorials/linalg/linear_systems.ipynb
Labels: documentation

#529 Fix broken link in development tutorial on testing
  docs/source/development/unit_testing.ipynb
Labels: bug, documentation

#494 [PLS Refactor] Linear solver information operators
  docs/source/api/linalg/solvers.information_ops.rst
  docs/source/api/linalg/solvers.rst
  src/probnum/linalg/solvers/__init__.py
  src/probnum/linalg/solvers/information_ops/__init__.py
  src/probnum/linalg/solvers/information_ops/_linear_solver_info_op.py
  src/probnum/linalg/solvers/information_ops/_matvec.py
  src/probnum/linalg/solvers/information_ops/_proj_residual.py
  src/probnum/linalg/solvers/policies/_linear_solver_policy.py
  src/probnum/linalg/solvers/policies/_random_unit_vector.py
  tests/test_linalg/test_solvers/cases/information_ops.py
  tests/test_linalg/test_solvers/cases/states.py
  tests/test_linalg/test_solvers/test_information_ops/__init__.py
  tests/test_linalg/test_solvers/test_information_ops/test_linear_solver_info_op.py
  tests/test_linalg/test_solvers/test_information_ops/test_matvec.py
  tests/test_linalg/test_solvers/test_information_ops/test_residual.py
  tests/test_linalg/test_solvers/test_policies/test_conjugate_gradient.py
Labels: refactoring, linalg

#535 Update `apt` cache in Github action running notebooks
  .github/workflows/run-notebooks.yml
  docs/source/research/bibliography/related.bib
Labels: bug, testing and CI

#499 [PLS Refactor] Linear solver stopping criteria
  docs/source/api/linalg/solvers.rst
  docs/source/api/linalg/solvers.stopping_criteria.rst
  src/probnum/linalg/solvers/information_ops/_linear_solver_info_op.py
  src/probnum/linalg/solvers/information_ops/_matvec.py
  src/probnum/linalg/solvers/information_ops/_proj_residual.py
  src/probnum/linalg/solvers/stopping_criteria/__init__.py
  src/probnum/linalg/solvers/stopping_criteria/_linear_solver_stopping_criterion.py
  src/probnum/linalg/solvers/stopping_criteria/_maxiter.py
  src/probnum/linalg/solvers/stopping_criteria/_posterior_contraction.py
  src/probnum/linalg/solvers/stopping_criteria/_residual_norm.py
  tests/test_linalg/test_solvers/cases/states.py
  tests/test_linalg/test_solvers/cases/stopping_criteria.py
  tests/test_linalg/test_solvers/test_stopping_criteria/__init__.py
  tests/test_linalg/test_solvers/test_stopping_criteria/test_linear_solver_stopping_criterion.py
  tests/test_linalg/test_solvers/test_stopping_criteria/test_maxiter.py
  tests/test_linalg/test_solvers/test_stopping_criteria/test_posterior_contraction.py
  tests/test_linalg/test_solvers/test_stopping_criteria/test_residual_norm.py
Labels: refactoring, linalg

#534 linops quickstart
  docs/source/tutorials.rst
  docs/source/tutorials/linops/linear_operators.ipynb
  docs/source/tutorials/linops/linear_operators_quickstart.ipynb
Labels: documentation
