Repository probabilistic-numerics/probnum, pull requests merged in 2021-05, with the labels that each got.

#391 Kronecker __matmul__ bugfix
  src/probnum/linops/_kronecker.py
  src/probnum/linops/_linear_operator.py
  tests/test_linops/test_linops.py
Labels: bug, linalg

#392 Performance fixes in Kronecker __matmul__
  src/probnum/linops/_kronecker.py
Labels: improvement, linalg, refactoring

#389 Implement filtsmooth methods as generators
  benchmarks/filtsmooth.py
  docs/source/tutorials/filtsmooth/linear_gaussian_filtering_smoothing.ipynb
  docs/source/tutorials/filtsmooth/nonlinear_gaussian_filtering_smoothing.ipynb
  docs/source/tutorials/filtsmooth/particle_filtering.ipynb
  src/probnum/diffeq/odefiltsmooth/initialize.py
  src/probnum/filtsmooth/gaussfiltsmooth/kalman.py
  src/probnum/filtsmooth/particlefiltsmooth/_particle_filter.py
  tests/test_diffeq/test_odefiltsmooth/test_kalman_odesolution.py
  tests/test_filtsmooth/filtsmooth_testcases.py
  tests/test_filtsmooth/test_gaussfiltsmooth/test_iterated_kalman.py
  tests/test_filtsmooth/test_gaussfiltsmooth/test_kalman.py
  tests/test_filtsmooth/test_gaussfiltsmooth/test_kalmanposterior.py
  tests/test_filtsmooth/test_particlefiltsmooth/test_particle_filter.py
Labels: filtsmooth

#397 Fix required Python version for numpy > 1.19.1
  requirements.txt
  setup.cfg
Labels: bug, dependencies

#408 Pylint `probnum.statespace`
  src/probnum/statespace/transition.py
  tox.ini
Labels: bug, statespace, testing and CI

#406 Update `setup.cfg` to new key descriptors
  setup.cfg
Labels: documentation
