Repository probabilistic-numerics/probnum, pull requests merged in 2021-03, with the labels that each got.

#333 Touchup for ODE and Filtering Tutorials
  docs/source/tutorials/bayesian_filtering_smoothing.rst
  docs/source/tutorials/filtsmooth/linear_bayesian_filtering_smoothing.ipynb
  docs/source/tutorials/filtsmooth/nonlinear_bayesian_filtering_smoothing.ipynb
  docs/source/tutorials/odes/adaptive_steps_odefilter.ipynb
  docs/source/tutorials/odes/uncertainties_odefilters.ipynb
Labels: documentation

#338 Styleguide and developer docs updated
  CONTRIBUTING.md
  STYLEGUIDE.md
  docs/source/development/creating_an_example_notebook.ipynb
Labels: documentation

#328 Move `statespace` module out of `filtsmooth` into top level
  docs/source/index.rst
  docs/source/public_api/filtsmooth.rst
  docs/source/public_api/statespace.rst
  docs/source/tutorials/odes/odesolvers_from_scratch.ipynb
  src/probnum/__init__.py
  src/probnum/diffeq/odefiltsmooth/initialize.py
  src/probnum/diffeq/odefiltsmooth/ivpfiltsmooth.py
  src/probnum/diffeq/odefiltsmooth/odefiltsmooth.py
  src/probnum/filtsmooth/gaussfiltsmooth/extendedkalman.py
  src/probnum/filtsmooth/gaussfiltsmooth/iterated_component.py
  src/probnum/filtsmooth/gaussfiltsmooth/unscentedkalman.py
  src/probnum/problems/_problems.py
  src/probnum/statespace/__init__.py
  src/probnum/statespace/discrete_transition.py
  src/probnum/statespace/discrete_transition_utils.py
  src/probnum/statespace/generate_samples.py
  src/probnum/statespace/integrator.py
  src/probnum/statespace/preconditioner.py
  src/probnum/statespace/sde.py
  src/probnum/statespace/sde_utils.py
  src/probnum/statespace/transition.py
  tests/test_diffeq/test_odefiltsmooth/test_initialize.py
  tests/test_diffeq/test_odefiltsmooth/test_ivp2filter.py
  tests/test_filtsmooth/test_gaussfiltsmooth/filtsmooth_testcases.py
  tests/test_filtsmooth/test_gaussfiltsmooth/test_iterated_kalman.py
  tests/test_filtsmooth/test_gaussfiltsmooth/test_kalman.py
  tests/test_filtsmooth/test_gaussfiltsmooth/test_kalmanposterior.py
  tests/test_filtsmooth/test_gaussfiltsmooth/test_unscentedkalman.py
  tests/test_statespace/__init__.py
  tests/test_statespace/conftest.py
  tests/test_statespace/test_discrete_transition.py
  tests/test_statespace/test_discrete_transition_utils.py
  tests/test_statespace/test_generate_samples.py
  tests/test_statespace/test_integrator.py
  tests/test_statespace/test_preconditioner.py
  tests/test_statespace/test_sde.py
  tests/test_statespace/test_sde_utils.py
  tests/test_statespace/test_transition.py
Labels: filtsmooth, refactoring

#357 Automated versioning based on package metadata
  .github/workflows/python-publish.yml
  .gitignore
  setup.cfg
  setup.py
Labels: testing and CI

#360 Run Jupyter Notebooks in CI
  .github/workflows/run-notebooks.yml
  apt.txt
  docs/notebook-requirements.txt
  docs/requirements.txt
  docs/source/development/adding_to_the_api_documentation.ipynb
  docs/source/development/implementing_a_probnum_method.ipynb
  docs/source/development/quadopt_example/__init__.py
  docs/source/development/quadopt_example/_probsolve_qp.py
  docs/source/development/quadopt_example/belief_updates.py
  docs/source/development/quadopt_example/observation_operators.py
  docs/source/development/quadopt_example/policies.py
  docs/source/development/quadopt_example/probabilistic_quadratic_optimizer.py
  docs/source/development/quadopt_example/stopping_criteria.py
  docs/source/introduction/quickstart.ipynb
  docs/sphinx-requirements.txt
  environment.yml
Labels: documentation, testing and CI

#366 Refactor linop testing using pytest-cases
  setup.cfg
  src/probnum/linops/_arithmetic.py
  src/probnum/linops/_kronecker.py
  src/probnum/linops/_linear_operator.py
  src/probnum/randvars/_normal.py
  tests/test_linops/test_kronecker.py
  tests/test_linops/test_linearoperators.py
  tests/test_linops/test_linops.py
  tests/test_linops/test_linops_cases/__init__.py
  tests/test_linops/test_linops_cases/kronecker_cases.py
  tests/test_linops/test_linops_cases/linear_operator_cases.py
Labels: improvement, linalg, refactoring, testing and CI
