Repository probabilistic-numerics/probnum, pull requests merged in 2021-08, with the labels that each got.

#510 renaming randvars tutorial to quickstart
  docs/source/tutorials.rst
  docs/source/tutorials/prob/random_variables.ipynb
  docs/source/tutorials/prob/random_variables_quickstart.ipynb
Labels: documentation

#498 Event handling for ODE solvers
  docs/source/api/diffeq.rst
  docs/source/api/diffeq/callbacks.rst
  docs/source/tutorials.rst
  docs/source/tutorials/odes/event_handling.ipynb
  docs/source/tutorials/odes/odesolvers_from_scratch.ipynb
  src/probnum/diffeq/__init__.py
  src/probnum/diffeq/_odesolver.py
  src/probnum/diffeq/_odesolver_state.py
  src/probnum/diffeq/_perturbsolve_ivp.py
  src/probnum/diffeq/_probsolve_ivp.py
  src/probnum/diffeq/callbacks/__init__.py
  src/probnum/diffeq/callbacks/_callback.py
  src/probnum/diffeq/callbacks/_discrete_callback.py
  src/probnum/diffeq/odefiltsmooth/_ivpfiltsmooth.py
  src/probnum/diffeq/perturbed/scipy_wrapper/_wrapped_scipy_solver.py
  src/probnum/diffeq/perturbed/step/_perturbedstepsolver.py
  tests/test_diffeq/test_callbacks/__init__.py
  tests/test_diffeq/test_callbacks/_callback_test_interface.py
  tests/test_diffeq/test_callbacks/test_discrete_callback.py
  tests/test_diffeq/test_odefiltsmooth/test_ivpfiltsmooth.py
  tests/test_diffeq/test_odesolver.py
  tests/test_diffeq/test_perturbed/test_scipy_wrapper/test_wrapped_scipy_odesolution.py
  tests/test_diffeq/test_perturbed/test_scipy_wrapper/test_wrapped_scipy_solver.py
  tests/test_diffeq/test_perturbed/test_step/test_perturbedstepsolver.py
  tests/test_diffeq/test_perturbsolve_ivp.py
  tests/test_diffeq/test_probsolve_ivp.py
Labels: diffeq, improvement

#501 Improve SDE API
  benchmarks/randprocs.py
  docs/source/tutorials/filtsmooth/linear_gaussian_filtering_smoothing.ipynb
  docs/source/tutorials/filtsmooth/nonlinear_gaussian_filtering_smoothing.ipynb
  docs/source/tutorials/filtsmooth/particle_filtering.ipynb
  src/probnum/diffeq/odefilter/information_operators/_information_operator.py
  src/probnum/diffeq/odefilter/initialization_routines/_runge_kutta.py
  src/probnum/diffeq/odefilter/utils/_problem_utils.py
  src/probnum/filtsmooth/_kalman_filter_smoother.py
  src/probnum/filtsmooth/gaussian/_kalman.py
  src/probnum/filtsmooth/gaussian/_kalmanposterior.py
  src/probnum/filtsmooth/gaussian/approx/_extendedkalman.py
  src/probnum/filtsmooth/gaussian/approx/_unscentedkalman.py
  src/probnum/filtsmooth/optim/_iterated_component.py
  src/probnum/filtsmooth/particle/_particle_filter.py
  src/probnum/problems/_problems.py
  src/probnum/problems/zoo/filtsmooth/_filtsmooth_problems.py
  src/probnum/randprocs/markov/_transition.py
  src/probnum/randprocs/markov/continuous/__init__.py
  src/probnum/randprocs/markov/continuous/_linear_sde.py
  src/probnum/randprocs/markov/continuous/_lti_sde.py
  src/probnum/randprocs/markov/continuous/_mfd.py
  src/probnum/randprocs/markov/continuous/_sde.py
  src/probnum/randprocs/markov/discrete/__init__.py
  src/probnum/randprocs/markov/discrete/_linear_gaussian.py
  src/probnum/randprocs/markov/discrete/_lti_gaussian.py
  src/probnum/randprocs/markov/discrete/_nonlinear_gaussian.py
  src/probnum/randprocs/markov/integrator/_integrator.py
  src/probnum/randprocs/markov/integrator/_ioup.py
  src/probnum/randprocs/markov/integrator/_iwp.py
  src/probnum/randprocs/markov/integrator/_matern.py
  tests/test_diffeq/test_odefilter/test_information_operators/test_ode_residual.py
  tests/test_diffeq/test_odefilter/test_utils/test_problem_utils.py
  tests/test_filtsmooth/test_gaussian/test_approx/test_unscentedkalman.py
  tests/test_filtsmooth/test_gaussian/test_kalmanposterior.py
  tests/test_randprocs/test_markov/test_continuous/test_linear_sde.py
  tests/test_randprocs/test_markov/test_continuous/test_lti_sde.py
  tests/test_randprocs/test_markov/test_continuous/test_sde.py
  tests/test_randprocs/test_markov/test_discrete/test_linear_gaussian.py
  tests/test_randprocs/test_markov/test_discrete/test_lti_gaussian.py
  tests/test_randprocs/test_markov/test_discrete/test_nonlinear_gaussian.py
  tests/test_randprocs/test_markov/test_integrator/test_integrator.py
  tests/test_randprocs/test_markov/test_integrator/test_ioup.py
  tests/test_randprocs/test_markov/test_integrator/test_iwp.py
  tests/test_randprocs/test_markov/test_integrator/test_matern.py
  tests/test_randprocs/test_markov/test_markov_process.py
Labels: refactoring, statespace

#522 Remove globally disabled `pylint` messages
  .github/workflows/linting.yml
  .github/workflows/pylint_check.py
  pyproject.toml
  src/probnum/__init__.py
  src/probnum/_config.py
  src/probnum/kernels/_kernel.py
  src/probnum/linops/_scaling.py
  src/probnum/problems/zoo/linalg/_suitesparse_matrix.py
  src/probnum/randvars/_normal.py
  tox.ini
Labels: bug, refactoring, testing and CI

#525 Restructure `.gitignore`
  .gitignore
  benchmarks/.gitignore
  docs/.gitignore
Labels: refactoring

#527 Bugfix: Deploy to PyPI
  .github/workflows/python-publish.yml
Labels: bug, testing and CI
