Repository probabilistic-numerics/probnum, pull requests merged in 2022-02, with the labels that each got.

#623 Small documentation fixes and updates to roles
  docs/source/development.md
  docs/source/tutorials/odes/adaptive_steps_odefilter.ipynb
  docs/source/tutorials/odes/event_handling.ipynb
  docs/source/tutorials/pn_methods.ipynb
Labels: documentation

#580 Reorthogonalization for a stable implementation of the probabilistic linear solver
  src/probnum/linalg/solvers/_state.py
  src/probnum/linalg/solvers/belief_updates/solution_based/_solution_based_proj_rhs_belief_update.py
  src/probnum/linalg/solvers/beliefs/_linear_system_belief.py
  src/probnum/linalg/solvers/policies/_conjugate_gradient.py
  src/probnum/utils/linalg/__init__.py
  src/probnum/utils/linalg/_inner_product.py
  src/probnum/utils/linalg/_orthogonalize.py
  tests/test_linalg/cases/linear_systems.py
  tests/test_linalg/test_solvers/cases/policies.py
  tests/test_linalg/test_solvers/conftest.py
  tests/test_linalg/test_solvers/test_policies/test_conjugate_gradient.py
  tests/test_linalg/test_solvers/test_policies/test_linear_solver_policy.py
  tests/test_utils/test_linalg/test_inner_product.py
  tests/test_utils/test_linalg/test_orthogonalize.py
Labels: linalg, improvement

#636 Clean up ProbNum's Development Dependencies
  benchmarks/requirements.txt
  dev-requirements.txt
  formatting-requirements.txt
  linting-requirements.txt
  setup.cfg
  tests/requirements.txt
  tox.ini
Labels: testing and CI, dependencies

#588 Row selection policy for the PLS
  src/probnum/linalg/solvers/policies/_random_unit_vector.py
  tests/test_linalg/test_solvers/cases/policies.py
  tests/test_linalg/test_solvers/test_policies/test_random_unit_vector.py
Labels: linalg, improvement

#640 `codecov/codecov-action` instead of bash uploader
  .github/workflows/CI-build.yml
Labels: testing and CI

#639 Add `Function` class and refactor `RandomProcess.{input,output}_{dim => shape}`
  benchmarks/kernels.py
  docs/source/api/randprocs.rst
  docs/source/api/randprocs/mean_fns.rst
  src/probnum/__init__.py
  src/probnum/_function.py
  src/probnum/quad/kernel_embeddings/_expquad_gauss.py
  src/probnum/quad/kernel_embeddings/_expquad_lebesgue.py
  src/probnum/quad/kernel_embeddings/_kernel_embedding.py
  src/probnum/quad/solvers/bayesian_quadrature.py
  src/probnum/randprocs/__init__.py
  src/probnum/randprocs/_gaussian_process.py
  src/probnum/randprocs/_random_process.py
  src/probnum/randprocs/kernels/_exponentiated_quadratic.py
  src/probnum/randprocs/kernels/_kernel.py
  src/probnum/randprocs/kernels/_linear.py
  src/probnum/randprocs/kernels/_matern.py
  src/probnum/randprocs/kernels/_polynomial.py
  src/probnum/randprocs/kernels/_rational_quadratic.py
  src/probnum/randprocs/kernels/_white_noise.py
  src/probnum/randprocs/markov/_markov_process.py
  src/probnum/randprocs/markov/integrator/_ioup.py
  src/probnum/randprocs/markov/integrator/_iwp.py
  src/probnum/randprocs/markov/integrator/_matern.py
  src/probnum/randprocs/mean_fns.py
  tests/test_function.py
  tests/test_linalg/cases/matrices.py
  tests/test_quad/conftest.py
  tests/test_randprocs/conftest.py
  tests/test_randprocs/test_gaussian_process.py
  tests/test_randprocs/test_kernels/conftest.py
  tests/test_randprocs/test_kernels/test_call.py
  tests/test_randprocs/test_kernels/test_matern.py
  tests/test_randprocs/test_kernels/test_matrix.py
  tests/test_randprocs/test_kernels/test_rational_quadratic.py
  tests/test_randprocs/test_random_process.py
  tox.ini
Labels: refactoring, improvement, prob

#649 [Bugfix] Scalar arguments in `Kernel.__call__`
  src/probnum/_function.py
  src/probnum/randprocs/kernels/_exponentiated_quadratic.py
  src/probnum/randprocs/kernels/_kernel.py
  src/probnum/randprocs/kernels/_rational_quadratic.py
  tox.ini
Labels: bug

#650 Remove `input_shape` broadcasting capabilities from `Kernel`
  src/probnum/_function.py
  src/probnum/randprocs/kernels/_exponentiated_quadratic.py
  src/probnum/randprocs/kernels/_kernel.py
  src/probnum/randprocs/kernels/_rational_quadratic.py
  src/probnum/randprocs/kernels/_white_noise.py
  tests/test_randprocs/test_kernels/_utils.py
  tests/test_randprocs/test_kernels/conftest.py
  tests/test_randprocs/test_kernels/test_call.py
  tests/test_randprocs/test_kernels/test_matern.py
  tests/test_randprocs/test_kernels/test_matrix.py
Labels: refactoring

#652 `Kernel.output_shape` semantics and further `RandomProcess` refactoring
  src/probnum/_function.py
  src/probnum/randprocs/_gaussian_process.py
  src/probnum/randprocs/_random_process.py
  src/probnum/randprocs/kernels/_kernel.py
  src/probnum/randprocs/kernels/_matern.py
  src/probnum/randprocs/markov/_markov_process.py
  tests/test_randprocs/test_random_process.py
Labels: bug, refactoring, improvement, prob

#653 Add support for Python 3.10
  .github/workflows/CI-build.yml
  setup.cfg
Labels: testing and CI, dependencies
