Repository probabilistic-numerics/probnum, pull requests merged in 2022-01, with the labels that each got.

#600 Refactor `as_numpy_scalar` to produce scalar `np.ndarray`s
  src/probnum/randvars/_random_variable.py
  src/probnum/typing.py
  src/probnum/utils/argutils.py
  tests/test_linops/test_linops.py
  tests/test_randvars/test_normal.py
  tests/test_utils/test_argutils.py
Labels: refactoring

#596 citation request in readme
  README.md
Labels: documentation

#602 `__(r)matmul__` of `Matrix` linear operator outputs `np.matrix`
  src/probnum/linops/_linear_operator.py
  tests/test_linops/test_matrix.py
Labels: bug, linops

#604 Correct links in footer of documentation
  docs/source/_templates/footer.html
Labels: bug, documentation

#610 pylint cleanup quad
  src/probnum/quad/_bayesquad.py
  src/probnum/quad/kernel_embeddings/_expquad_gauss.py
  src/probnum/quad/kernel_embeddings/_expquad_lebesgue.py
  src/probnum/quad/kernel_embeddings/_kernel_embedding.py
  src/probnum/quad/solvers/bayesian_quadrature.py
  src/probnum/quad/solvers/belief_updates/_belief_update.py
  src/probnum/quad/solvers/bq_state.py
  src/probnum/quad/solvers/policies/_policy.py
  src/probnum/quad/solvers/stopping_criteria/_bq_stopping_criterion.py
  src/probnum/quad/solvers/stopping_criteria/_rel_mean_change.py
  tox.ini
Labels: quad

#616 Additions to the global pylint configuration
  pyproject.toml
  tox.ini
Labels: testing and CI

#617 Another additions to the global pylint configuration
  pyproject.toml
  tox.ini
Labels: testing and CI

#618 Cholesky decompositions of `LinearOperator`s
  src/probnum/linops/_arithmetic_fallbacks.py
  src/probnum/linops/_kronecker.py
  src/probnum/linops/_linear_operator.py
  src/probnum/linops/_scaling.py
  tests/test_linops/test_linop_decompositions.py
  tests/test_linops/test_linop_properties.py
  tests/test_linops/test_linops.py
  tests/test_linops/test_linops_cases/arithmetic_cases.py
  tests/test_linops/test_linops_cases/kronecker_cases.py
  tests/test_linops/test_linops_cases/linear_operator_cases.py
  tests/test_linops/test_linops_cases/scaling_cases.py
Labels: improvement, linops
